---
title: "Analysis of 2013"
output: html_document
---


```{r plot1 , echo=FALSE,results='hide',message=FALSE}




Data<-read.csv("Dataset.csv")

data2013<-Data[Data$Year==2013,]

LE_data2013<-data.frame(Code=Country_Code,Life.Exp=Life_Expectancy_At_Birth_2013)



merged2013<-merge(data2013,LE_data2013,by.x ="Country.Code",by.y = "Code")

merged2013$Year<-NULL


library(ggplot2)

qplot(data=merged2013,x=Fertility.Rate,y=Life.Exp,color=Region,size=I(2),shape=I(17),alpha=I(0.7),main = "Life Expectancy Vs Fertility(2013)")

kable(merged2013[,],caption = "Table for datsets for year 2013")


colnames(merged2013)<-c("Counrty Code","Country Name","Region","Fertility Rate ","Life Expectancy")


```



##PLOT

The Above shows a Visualizaton of  Quick Plot for  Life Expectancy Vs Fertility for the year 2013 from datasets containing data's for all countries.


```{r table1 , echo=FALSE,message=FALSE}

kable(merged2013[,],caption = "Knitr Table for the  year 2013")


```








##SUMMARY


The Above is a Knitr Table  containing data based on "Life Expectancy vs Fertility Rate Analysis " for the Year 2013 for all countries.

